# Inspiration from https://docs.docker.com/samples/wordpress/
# Wordpress Docker cluster with:
# - phpmyadmin for DB digging
# - WP-CLI for Wordpress CLI config


version: "3.9"
    
services:
  db:
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - type: bind
        source: ${LOCAL_DB_DIR}
        target: /var/lib/mysql
    restart: always
    ports:
      - "33060:3306"
    networks:
      - wp_net
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    container_name: ${PHPMYADMIN_NAME}
    depends_on:
      - db
      - wordpress
    image: phpmyadmin:latest
    links:
     - db
    restart: always
    ports:
      - 8082:80
    networks:
      - wp_net
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - type: bind
        source: ${LOCAL_WP_DIR}
        target: /var/www/html
    ports:
      - "${WP_EXT_PORT}:80"
    networks:
      - wp_net
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: "true"

  wordpress-toolbox:
    image: wordpress:cli
    container_name: ${PROJECT_NAME}_wordpress-toolbox
    depends_on:
      - db
      - wordpress
    links:
      - db
    volumes:
      - ${LOCAL_WP_DIR}:/var/www/html
      - ./docker/wordpress-cli/install.sh:/install.sh
    working_dir: /var/www/html
    networks:
      - wp_net
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_WEBSITE_TITLE: 'My Auth0 Wordpress debugger'
      WORDPRESS_WEBSITE_URL: 'http://localhost:${WP_EXT_PORT}'
      WORDPRESS_WEBSITE_URL_WITHOUT_HTTP: 'localhost:${WP_EXT_PORT}'
      WORDPRESS_ADMIN_USER: 'admin'
      WORDPRESS_ADMIN_PASSWORD: 'admin'
      WORDPRESS_ADMIN_EMAIL: '${WP_EXT_PORT}'
      WORDPRESS_DEBUG: "true"


networks:
  wp_net: {}